# Generated by Django 3.0.5 on 2020-04-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='seed',
            field=models.URLField(blank=True),
        ),
    ]
